variables:
    ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
    SolutionBaseName: 'DFC.Api.Lmi.Transformation'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

trigger: 
  branches:
    include: 
    - dev
    - master

pr:
  branches:
    include: 
    - dev
    - master


stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: TestArmTemplates
    displayName: "Test ARM Templates"
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - task: PublishPipelineArtifact@1
      displayName: Publish Apim Policy
      inputs:
        targetPath: "$(Build.SourcesDirectory)/Resources/ApimPolicy"
        artifactName: ${{ variables.SolutionBaseName }}.ApimPolicies


  - job: BuildTestAndAnalyze
    displayName: "Build and test application"
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'

- stage: DeployToDevLmiTransformation
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_LMI_TRANSFORMATIONS
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-dev
  - group: dfc-compositeui-all
  - template: VariableTemplates\DevEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV_LMI_TRANSFORMATIONS
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      AppServiceName: '$(FunctionAppName)'
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: $(SharedResourceGroup)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      FunctionAppDomain: $(FunctionAppDomain)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"
      ApimApiName: $(ApimApiName)
      SubscriptionPosturi: '$(SubscriptionPosturi)'
      Apis:
        -
          - azureFunctionName: '${{ variables.FunctionAppName }}'

- stage: DeployToDevDraftLmiTransformation
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV-DRAFT_LMI_TRANSFORMATIONS
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-dev
  - group: dfc-compositeui-all
  - template: VariableTemplates\DevDraftEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV-DRAFT_LMI_TRANSFORMATIONS
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      AppServiceName: '$(FunctionAppName)'
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: $(SharedResourceGroup)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      FunctionAppDomain: $(FunctionAppDomain)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"
      SubscriptionPosturi: '$(SubscriptionPosturi)'
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.FunctionAppName }}'

- stage: DeployToSitLmiTransformation
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT_LMI_TRANSFORMATIONS
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-sit
  - group: dfc-compositeui-all
  - template: VariableTemplates\SitEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT_LMI_TRANSFORMATIONS
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      AppServiceName: '$(FunctionAppName)'
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: $(SharedResourceGroup)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      FunctionAppDomain: $(FunctionAppDomain)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"
      SubscriptionPosturi: '$(SubscriptionPosturi)'
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.FunctionAppName }}'

- stage: DeployToSitDraftLmiTransformation
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT-DRAFT_LMI_TRANSFORMATIONS
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-sit
  - group: dfc-compositeui-all
  - template: VariableTemplates\SitDraftEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT-DRAFT_LMI_TRANSFORMATIONS
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      AppServiceName: '$(FunctionAppName)'
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: $(SharedResourceGroup)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      FunctionAppDomain: $(FunctionAppDomain)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"
      SubscriptionPosturi: '$(SubscriptionPosturi)'
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.FunctionAppName }}'
