variables:
- name: ReleaseEnvironmentName
  value: SIT
- name: WebAppPrefix
  value: dfc-sit-api-lmi-transformation
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: lmiTransformationAppDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosJobGroupDbCollectionName
  value: job-groups
- name: contentUrl
  value: $(ContentApiAddress)/api/execute/
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/LMI/Transformation/lmi/webhook?subscription-key=$(apimLmiKey)
- name: subscriptionUrl
  value: https://dfc-sit-api-eventgridsubscriptions-fa.$(FunctionAppDomain)/api/execute/
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://$(FunctionAppName).$(FunctionAppDomain)/job-groups
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/
- name: FunctionAppName
  value: $(WebAppPrefix)-fa
- name: ApplicationName
  value: dfc-api-lmi-transformation
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Transformation
- name: SubscriptionPosturi
  value: https://$(FunctionAppName).$(FunctionAppDomain)/subscription/
- name: FunctionAppUrl
  value: https://$(FunctionAppName).$(FunctionAppDomain)